In [2]:
from tensorflow import keras

def build_target_network(input_shape,n_outputs): 
        target_network = keras.models.Sequential([
            keras.layers.Dense(444, activation='relu', input_shape = input_shape), 
            keras.layers.Dense(200,activation='relu'),
            keras.layers.Dense(124, activation='relu'),
            keras.layers.Dense(64, activation='relu'),
            keras.layers.Dense(n_outputs)])
        return target_network 


In [7]:
import numpy as np

In [4]:
targt_network = build_target_network((4,),n_outputs=6)

In [6]:
targt_network.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 444)               2220      
                                                                 
 dense_6 (Dense)             (None, 200)               89000     
                                                                 
 dense_7 (Dense)             (None, 124)               24924     
                                                                 
 dense_8 (Dense)             (None, 64)                8000      
                                                                 
 dense_9 (Dense)             (None, 6)                 390       
                                                                 
Total params: 124,534
Trainable params: 124,534
Non-trainable params: 0
_________________________________________________________________


In [31]:
state_1 = np.array([3, 4, 5, 6])
state_2 = np.array([1, 2, 3, 4])

# Combine into a batch
batch_states = np.array([state_1, state_2])

In [32]:
target_Q_values_1 = targt_network.predict(batch_states)
selected_actions = np.argmax(target_Q_values_1, axis=1)
target_Q_values = target_Q_values_1[np.arange(target_Q_values_1.shape[0]), selected_actions]


1/1 [==============================] - 0s 9ms/step


In [37]:
target_Q_values_1

array([[-0.057608  ,  0.57187176, -0.39172256, -0.8587368 , -0.28449932,
         0.19463642],
       [ 0.01017386,  0.31247956, -0.2020368 , -0.50926334, -0.1818652 ,
         0.08571875]], dtype=float32)

In [36]:
np.arange(target_Q_values_1.shape[0])

array([0, 1])

In [33]:
target_Q_values_1

array([[-0.057608  ,  0.57187176, -0.39172256, -0.8587368 , -0.28449932,
         0.19463642],
       [ 0.01017386,  0.31247956, -0.2020368 , -0.50926334, -0.1818652 ,
         0.08571875]], dtype=float32)

In [35]:
target_Q_values

array([0.57187176, 0.31247956], dtype=float32)

In [59]:
np.random.rand()

0.5097244245480086