In [66]:
from collections import deque 
import numpy as np 
replay_memory = deque(maxlen=2000)
import tensorflow as tf
from tensorflow import keras 

In [67]:
model = keras.models.Sequential([
    keras.layers.Dense(128, activation="elu", input_shape=[3]),
    keras.layers.Dense(64, activation="elu"),
    keras.layers.Dense(4)
])

In [68]:
# Example 3
state3 = [0.5, 0.6, 0.7]
action3 = 2
reward3 = 0.1
next_state3 = [0.6, 0.7, 0.8]
done3 = False
truncated3 = True

experience3 = (state3, action3, reward3, next_state3, done3, truncated3)
replay_memory.append(experience3)

# Example 4
state4 = [0.7, 0.8, 0.9]
action4 = 1
reward4 = 0.8
next_state4 = [0.8, 0.9, 1.0]
done4 = False
truncated4 = False

experience4 = (state4, action4, reward4, next_state4, done4, truncated4)
replay_memory.append(experience4)

# Example 5
state5 = [1.0, 1.1, 1.2]
action5 = 0
reward5 = -0.5
next_state5 = [1.1, 1.2, 1.3]
done5 = True
truncated5 = False

experience5 = (state5, action5, reward5, next_state5, done5, truncated5)
replay_memory.append(experience5)

# Example 6
state6 = [1.2, 1.3, 1.4]
action6 = 2
reward6 = 0.3
next_state6 = [1.3, 1.4, 1.5]
done6 = False
truncated6 = True

experience6 = (state6, action6, reward6, next_state6, done6, truncated6)
replay_memory.append(experience6)

# Example 7
state7 = [1.5, 1.6, 1.7]
action7 = 1
reward7 = 0.2
next_state7 = [1.6, 1.7, 1.8]
done7 = True
truncated7 = False

experience7 = (state7, action7, reward7, next_state7, done7, truncated7)
replay_memory.append(experience7)

In [69]:
def sample_experiences(batch_size):
    indices = np.random.randint(len(replay_memory), size = batch_size)
    batch = [replay_memory[index] for index in indices] 
    return [   

        np.array([experience[field_index] for experience in batch]) 
        for field_index in range(6)
    ] 

In [88]:
states,actions,rewards,next_states,dones,truncateds = sample_experiences(3)


In [90]:
actions

array([2, 1, 1])

In [76]:
b = model.predict(states[np.newaxis])
b

1/1 [==============================] - 0s 13ms/step


array([[-0.01003715, -0.13977265, -0.03586976, -0.11430354]],
      dtype=float32)

In [78]:
b.shape

(1, 4)

In [77]:
a = tf.one_hot(rewards, outputs)
a


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]], dtype=float32)>

In [79]:
a.shape

TensorShape([3, 4])

In [85]:
b * a

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.        , -0.        , -0.03586976, -0.        ],
       [-0.        , -0.13977265, -0.        , -0.        ],
       [-0.        , -0.13977265, -0.        , -0.        ]],
      dtype=float32)>

In [92]:
Q_values = tf.reduce_sum(b * a, axis=1, keepdims=True)
Q_values

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[-0.03586976],
       [-0.13977265],
       [-0.13977265]], dtype=float32)>

In [94]:
possible_actions = [[0,1,2],[0,2],[1]]


In [100]:
Q_table = np.full((3, 3), -np.inf)

In [98]:
for state, actions in enumerate(possible_actions):
    print(actions)
    Q_table[state][actions] = 0

[0, 1, 2]
[0, 2]
[1]


In [104]:
Q_table[0][[0,1]] = 2 

In [105]:
Q_table

array([[  2.,   2., -inf],
       [-inf, -inf, -inf],
       [-inf, -inf, -inf]])

In [99]:
Q_table[0][[0,1,2]]

array([0., 0., 0.])

In [96]:
Q_table

array([[  0.,   0.,   0.],
       [  0., -inf,   0.],
       [-inf,   0., -inf]])